### ISSUE TITLE
Judder during initial battle slide in animation [Doublespeed-60fps-Running-Shoes Branch]

### ISSUE THREAD

**Issue by JySzE** [vulcandth/pokecrystal#4]
[Doublespeed-60fps-Running-Shoes Branch]

Judder during initial battle slide in animation for both you the trainer and enemy MON

I don't know if you would considering making this part of the battle animations higher fps to reduce the nasty judder, shin red was able to correct this but I was unable to figure it out in their source code and bring it over to crystal.

https://github.com/vulcandth/pokecrystal/assets/70117278/d241a69b-1aaf-4bab-aeee-cde79238d133

Thanks.

**Comment by JySzE** [comment]
Did some digging and it was fixed in polished crystal. 

https://github.com/Rangi42/polishedcrystal/commit/65b1137b4f0eaa676c3e35f4278eeeacb011f895

**Comment by vulcandth** [comment]
Should be resolved in https://github.com/fellowship-of-the-roms/pokecrystal/commit/3a82eda60ace9dff87d6433a0d14b1d1c3aa083e
