### ISSUE TITLE
Stutter inside Azalea Town Gym [Doublespeed-60fps-Running-Shoes Branch]

### ISSUE THREAD

**Issue by JySzE** [vulcandth/pokecrystal#5]
Regardless if walking or running the stuttering inside the Gym is extreme and objects like trainers flicker like crazy. 

I don't know if this is a engine limitation or something.

Tested on a GBA, GBA SP, Analogue Pocket, MGBA, BGB and Sameboy.

The stutter doesn't only occur in the Azalea Town Gym but its most noticeable there, you can also see it while running or walking left and right inside Azalea Town and in many other locations.

**Comment by vulcandth** [comment]
Moved issue to: fellowship-of-the-roms#3
